[package]
name = "nrg"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
image = { path = "external/image-rs" }
ttf-parser = { path = "external/ttf-parser" }

nrg_math = { path = "math" }
nrg_common = { path = "common" }
nrg_platform = { path = "platform" }
nrg_graphics = { path = "graphics" }
nrg_core = { path = "core" }