[workspace]

members = [
    "app",
    "core",
    "gui",
    "graphics",
    "math",
    "platform",
    "serialize",
    "bindings/vulkan_bindings",
    "game_renderer",
    "game_window",
    "game",
    "editor",
]
