[workspace]

members = [
    "apps/launcher_app",
    "apps/game_app",
    "apps/editor_app",
    "bindings/vulkan_bindings",
    "binarizer",
    "core",
    "events",
    "gui",
    "graphics",
    "dynamic_library",
    "math",
    "messenger",
    "platform",
    "profiler",
    "resources",
    "serialize",
    "window",
    "game",
]