[workspace]

members = [
    "apps/launcher_app",
    "apps/editor",
    "bindings/vulkan_bindings",
    "binarizer",
    "camera",
    "core",
    "events",
    "filesystem",
    "gui",
    "graphics",
    "math",
    "messenger",
    "platform",
    "profiler",
    "resources",
    "scene",
    "serialize",
    "ui",
]