[workspace]

members = [
    "apps/main_app",
    "apps/game_app",
    "apps/editor_app",
    "core",
    "events",
    "gui",
    "graphics",
    "math",
    "platform",
    "profiler",
    "resources",
    "serialize",
    "bindings/vulkan_bindings",
    "renderer",
    "window",
    "game",
    "editor",
]