[package]
name = "nrg"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrg_platform = { path = "platform" }
nrg_graphics = { path = "graphics" }
nrg_math = { path = "math" }
nrg_core = { path = "core" }