[workspace]

members = [
    "app",
    "core",
    "math",
    "platform",
    "serialize",
    "bindings/vulkan_bindings",
    "plugins/game",
    "plugins/graphics",
    "plugins/gui",
    "plugins/window",
]
