[workspace]

members = [
    "app",
    "core",
    "gui",
    "graphics",
    "math",
    "platform",
    "serialize",
    "bindings/vulkan_bindings",
    "plugins/editor",
    "plugins/game",
    "plugins/game_renderer",
    "plugins/game_window",
]
