[package]
name = "sabi_blender"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
name = "sabi_blender"
crate-type = ['cdylib', 'rlib']

[dependencies]
pyo3 = { path = "../../extern/pyo3", features = ["macros", "extension-module", "auto-initialize"] }
sabi_core = { path = "../core" }
sabi_graphics = { path = "../graphics" }
sabi_filesystem = { path = "../filesystem" }
sabi_math = { path = "../math" }
sabi_nodes = { path = "../nodes" }
sabi_resources = { path = "../resources" }
sabi_scene = { path = "../scene" }
sabi_serialize = { path = "../serialize" }