[package]
name = "inox_render"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
downcast-rs = { workspace = true }
image = { workspace = true }
ttf-parser = { workspace = true }
inox_bitmask = { path = "../bitmask" }
inox_bvh = { path = "../bvh" }
inox_commands = { path = "../commands" }
inox_core = { path = "../core" }
inox_filesystem = { path = "../filesystem" }
inox_log = { path = "../log" }
inox_math = { path = "../math" }
inox_messenger = { path = "../messenger" }
inox_platform = { path = "../platform" }
inox_resources = { path = "../resources" }
inox_profiler = { path = "../profiler" }
inox_serialize = { path = "../serialize" }
inox_uid = { path = "../uid" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { workspace = true }
futures = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
