[package]
name = "sabi_ui"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
egui = { path = "../../extern/egui/egui", features = ["multi_threaded"] }
image = { path = "../../extern/image" }

sabi_commands = { path = "../commands" }
sabi_core = { path = "../core" }
sabi_messenger = { path = "../messenger" }
sabi_math = { path = "../math" }
sabi_graphics = { path = "../graphics" }
sabi_platform = { path = "../platform" }
sabi_profiler = { path = "../profiler" }
sabi_resources = { path = "../resources" }
sabi_serialize = { path = "../serialize" }