[package]
name = "inox_ui"
build = "build.rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
egui = { workspace = true }
image = { workspace = true }
inox_commands = { path = "../commands" }
inox_core = { path = "../core" }
inox_log = { path = "../log" }
inox_messenger = { path = "../messenger" }
inox_math = { path = "../math" }
inox_filesystem = { path = "../filesystem" }
inox_platform = { path = "../platform" }
inox_render = { path = "../render" }
inox_profiler = { path = "../profiler" }
inox_resources = { path = "../resources" }
inox_serialize = { path = "../serialize" }
inox_uid = { path = "../uid" }