[package]
name = "inox_ui"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
egui = { path = "../../extern/egui/crates/egui" }
image = { path = "../../extern/image" }

inox_commands = { path = "../commands" }
inox_core = { path = "../core" }
inox_log = { path = "../log" }
inox_messenger = { path = "../messenger" }
inox_math = { path = "../math" }
inox_filesystem = { path = "../filesystem" }
inox_graphics = { path = "../graphics" }
inox_platform = { path = "../platform" }
inox_profiler = { path = "../profiler" }
inox_resources = { path = "../resources" }
inox_serialize = { path = "../serialize" }
inox_uid = { path = "../uid" }