[package]
name = "inox_bitmask"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }