[package]
name = "vulkan_bindings"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sabi_filesystem = { path = "../../filesystem"}

[build-dependencies]
bindgen = { path = "../../../extern/rust-bindgen"}
xml-rs = { path = "../../../extern/xml-rs" }

