[package]
name = "nrg_gui"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

[dependencies]
nrg_math = { path = "../math" }
nrg_graphics = { path = "../graphics" }
nrg_platform = { path = "../platform" }
nrg_serialize = { path = "../serialize" }