[package]
name = "inox_serialize"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
serde_derive = {version = "1.0"}
serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = { path = "../../extern/json"}
uuid = { path = "../../extern/uuid", features = ["serde", "v4", "v5"] }
inox_serializable = { path = "./serializable" }