[package]
name = "sabi_serialize"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
sabi_serialize_derive = { path = "./serialize_derive"}
serde_derive = {version = "1.0"}
serde = {version = "1.0", features = ["derive", "rc"]}
serde_json = { path = "../../extern/json"}
uuid = { path = "../../extern/uuid", features = ["serde", "v4", "v5"] }
erased-serde = { path = "../../extern/erased-serde" }
downcast-rs = { path = "../../extern/downcast-rs" }