[package]
name = "nrg_resources"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
nrg_filesystem = { path = "../filesystem" }
nrg_messenger = { path = "../messenger" }
nrg_profiler = { path = "../profiler" }
nrg_serialize = { path = "../serialize" }

#TO REMOVE
nrg_platform = { path = "../platform" }
