[package]
name = "nrg_core"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

[dependencies]
downcast-rs = { path = "../external/downcast-rs" }
nrg_platform = { path = "../platform" }