[build]
jobs = 4  # number of parallel jobs, defaults to # of CPUs
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "panic=abort"]
incremental = true            # whether or not to enable incremental compilation

[profile.dev]
split-debuginfo = "unpacked" # faster debug builds on mac

[profile.release]
# lto = true # VERY slightly smaller wasm
# opt-level = 's' # 10-20% smaller wasm compared to `opt-level = 3`
# opt-level = 1 # very slow and big wasm. Don't do this.
opt-level = 2 # fast and small wasm, basically same as `opt-level = 's'`
# opt-level = 3 # unecessarily large wasm for no performance gain

# debug = true # include debug symbols, useful when profiling wasm