pub mod link;
pub mod logic_context;
pub mod logic_data;
pub mod logic_nodes;
pub mod macros;
pub mod node;
pub mod node_registry;
pub mod node_tree;
pub mod pin;

pub use link::*;
pub use logic_context::*;
pub use logic_data::*;
pub use logic_nodes::*;
pub use macros::*;
pub use node::*;
pub use node_registry::*;
pub use node_tree::*;
pub use pin::*;

implement_pin_with_as_serializable!(f32);
implement_pin_with_as_serializable!(f64);
implement_pin_with_as_serializable!(u8);
implement_pin_with_as_serializable!(i8);
implement_pin_with_as_serializable!(u16);
implement_pin_with_as_serializable!(i16);
implement_pin_with_as_serializable!(u32);
implement_pin_with_as_serializable!(i32);
implement_pin_with_as_serializable!(bool);
implement_pin_with_as_serializable!(String);
