[package]
name = "inox_uid"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
uuid = { path = "../../extern/uuid", features = ["serde", "v4", "v5"] }