[package]
name = "nrg_serialize"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = {version = "1.0" }
serde_derive = {version = "1.0"}
serde = {version = "1.0", features = ["derive"]}
serde_json = {git = "https://github.com/serde-rs/json"}
