[package]
name = "nrg_serialize"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = {git = "https://github.com/serde-rs/json"}
