[package]
name = "image"
version = "0.23.12"
edition = "2018"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = ["The image-rs Developers"]
readme = "README.md"
documentation = "https://docs.rs/image"
repository = "https://github.com/image-rs/image"
homepage = "https://github.com/image-rs/image"
categories = ["multimedia::images", "multimedia::encoding"]
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]

[lib]
name = "image"
path = "./src/lib.rs"

[dependencies]
bytemuck = "1"
byteorder = "1.3.2"
num-iter = "0.1.32"
num-rational = { version = "0.3", default-features = false }
num-traits = "0.2.0"
gif = { version = "0.11.1", optional = true }
jpeg = { package = "jpeg-decoder", version = "0.1.17", default-features = false, optional = true }
png = { version = "0.16.5", optional = true }
scoped_threadpool = { version = "0.1", optional = true }
tiff = { version = "0.6.0", optional = true }
ravif = { version = "0.6.0", optional = true }
rgb = { version = "0.8.25", optional = true }
color_quant = "1.1"

[dev-dependencies]
crc32fast = "1.2.0"
num-complex = "0.3"
glob = "0.3"
quickcheck = "0.9"
criterion = "0.3"

[features]
default = ["gif", "jpeg", "ico", "png", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "dds", "farbfeld", "jpeg_rayon"]

ico = ["bmp", "png"]
pnm = []
tga = []
webp = []
bmp = []
hdr = ["scoped_threadpool"]
dxt = []
dds = ["dxt"]
farbfeld = []
# Enables multi-threading.
# Requires latest stable Rust.
jpeg_rayon = ["jpeg/rayon"]
# Non-default, enables avif encoding.
# Requires latest stable Rust.
avif = ["ravif", "rgb"]

# Build some inline benchmarks. Useful only during development.
# Requires rustc nightly for feature test.
benchmarks = []

[[bench]]
path = "benches/decode.rs"
name = "decode"
harness = false

[[bench]]
path = "benches/encode.rs"
name = "encode"
harness = false
