[package]
name = "sabi_scene"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
sabi_math = { path = "../math" }
sabi_nodes = { path = "../nodes" }
sabi_graphics = { path = "../graphics" }
sabi_messenger = { path = "../messenger" }
sabi_resources = { path = "../resources" }
sabi_serialize = { path = "../serialize" }
sabi_ui = { path = "../ui" }
