[package]
name = "inox_scene"
build = "build.rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
inox_core = { path = "../core" }
inox_math = { path = "../math" }
inox_nodes = { path = "../nodes" }
inox_filesystem = { path = "../filesystem" }
inox_messenger = { path = "../messenger" }
inox_profiler = { path = "../profiler" }
inox_render = { path = "../render" }
inox_resources = { path = "../resources" }
inox_serialize = { path = "../serialize" }
inox_time = { path = "../time" }
inox_ui = { path = "../ui" }
inox_uid = { path = "../uid" }
