[package]
name = "inox_scene"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
inox_core = { path = "../core" }
inox_math = { path = "../math" }
inox_nodes = { path = "../nodes" }
inox_graphics = { path = "../graphics" }
inox_messenger = { path = "../messenger" }
inox_profiler = { path = "../profiler" }
inox_resources = { path = "../resources" }
inox_serialize = { path = "../serialize" }
inox_time = { path = "../time" }
inox_ui = { path = "../ui" }
inox_uid = { path = "../uid" }
