[package]
name = "nrg_launcher"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"

[dependencies]
nrg_binarizer = { path = "../../binarizer" }
nrg_resources = { path = "../../resources" }
nrg_core = { path = "../../core" }
nrg_filesystem = { path = "../../filesystem" }
nrg_graphics = { path = "../../graphics" }
nrg_math = { path = "../../math" }
nrg_messenger = { path = "../../messenger" }
nrg_platform = { path = "../../platform" }
nrg_serialize = { path = "../../serialize" }

