[package]
name = "nrg_blender"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
name = "nrg_blender"
crate-type = ['cdylib', 'rlib']

[dependencies]
cpython = { path = "../extern/rust-cpython", version = "*", features = ["extension-module"] }