[package]
name = "sabi_messenger"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[dependencies]
sabi_commands = { path = "../commands" }
sabi_serialize = { path = "../serialize" }