[package]
name = "inox_time"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.79"
web-sys = {version = "0.3.56", features = ['Window', 'Performance', 'PerformanceTiming'] }
js-sys = "0.3.56"