[package]
name = "nrg_game_app"
version = "0.1.0"
authors = ["gents83 <gents83@gmail.com>"]
edition = "2018"

[dependencies]
nrg_core = { path = "../../core" }
nrg_dynamic_library = { path = "../../dynamic_library" }
