name: Blender addon Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  Blender-addon-deploy:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: "Deploy Blender Plugin"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./crates/blender/nrg_blender/NRG/  # default: public
          destination_dir: NRG

      - name: "Copy nrg_viewer configs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./data_raw/config/nrg_viewer  # default: public
          destination_dir: NRG/bin/data_raw/config/nrg_viewer

      - name: "Copy pipelines"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./data_raw/pipelines  # default: public
          destination_dir: NRG/bin/data_raw/pipelines

      - name: "Copy nrg_viewer configs"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./data_raw/shaders  # default: public
          destination_dir: NRG/bin/data_raw/shaders
