name: Rust

on:
  push:
    branches: [ gh-pages ]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  Create-zip-file:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip NRG
        run: zip -qq -r NRG.zip NRG
