name: Create Zip file

on:
  workflow_run:
    workflows: ["Rust"]
    branches: [main]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
    
jobs:
  Create-zip-file:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip NRG
        run: zip -qq -r NRG.zip NRG

      - name: Push zip file
        uses: test-room-7/action-update-file@v1
        with:
            file-path: NRG.zip
            branch: gh-pages
            commit-msg: Update NRG add-on for Blender
            github-token: ${{ secrets.GITHUB_TOKEN }}
