[package]
name = "inox_profiler"
build = "build.rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = { workspace = true, optional = true }
wgpu-profiler = { workspace = true, optional = true }
superluminal-perf = { workspace = true, optional = true }
serde_json = { workspace = true }
inox_filesystem = { path = "../filesystem" }
inox_log = { path = "../log" }
inox_platform = { path = "../platform" }

[features]
default = ["gpu", "chrometrace"]
gpu = ["dep:wgpu", "dep:wgpu-profiler"]
chrometrace = ["gpu"]
superluminal = ["dep:superluminal-perf"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }